### ISSUE TITLE
Example Slots do not have results

### ISSUE THREAD

**Issue by ericmontepanda** [cerner/fhir.cerner.com#378]
`Slot?schedule.actor=Practitioner/2578010&start=2019&slot-type=http://snomed.info/sct|408443003&_count=5`

Does not result in any slots for start dates in 2019 or 2020. Initial Issue at #377

**Comment by FFSol** [comment]
Hi Eric,

Each example I provided in #377 were re-tested before posting, and I just re-tested your given URL against our open endpoint (fhir-open.sandboxcerner.com) with results returned. Since you're making a request against our server and are certain that you're not getting results, I can check the logs if you can provide the x-request-id. 

For context, here is the full URL against our DSTU2 open endpoint:

```https://fhir-open.sandboxcerner.com/dstu2/0b8a0111-e8e6-4c26-a91c-5069cbc6b1ca/Slot?schedule.actor=Practitioner/2578010&start=2019&slot-type=http://snomed.info/sct|408443003&_count=5```

**Comment by ericmontepanda** [comment]
Thanks. I see what's happening. The tenant environment I have is different from what you posted, hence the data inconsistency. I was using a sandbox cerner id, and now in business.
