### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by cravelight** [cerner/fhir.cerner.com#97]
Has anyone considered publishing a swagger spec for this api?  That would reduce the manual documentation work to conceptual topics only.

http://swagger.io/

We generate the swagger spec on our api's from code comments.  It's really pretty easy to set up and very helpful.

**Comment by daliboz** [comment]
The FHIR standard itself is considering what it can and can't do with swagger, and we've been watching that with interest. Since most of our field and parameter definitions come from the core specification, or the standard profiles built from that specification, we would likely just build on the result of that investigation: https://chat.fhir.org/#narrow/stream/implementers/subject/Swagger.20and.20RAML

In addition: FHIR itself provides some automation around this in the form of the conformance documentation (states query parameters and documentation for them, and links to profiles that define the fields returned): http://hl7.org/fhir/dstu2/conformance.html

We are currently looking at other ways to produce our documentation, including swagger. However, that is not something we're doing as an immediate project. For now, I'll close this since it's not something we would be doing *right now,* and there are still a lot of internal and external conversations around how to generate our documentation.
